// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/voucherds.proto

package lsvoucherds

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Ping rpc to check that handler respond
type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{0}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

type PingRes struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRes) Reset()         { *m = PingRes{} }
func (m *PingRes) String() string { return proto.CompactTextString(m) }
func (*PingRes) ProtoMessage()    {}
func (*PingRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{1}
}

func (m *PingRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRes.Unmarshal(m, b)
}
func (m *PingRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRes.Marshal(b, m, deterministic)
}
func (m *PingRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRes.Merge(m, src)
}
func (m *PingRes) XXX_Size() int {
	return xxx_messageInfo_PingRes.Size(m)
}
func (m *PingRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRes.DiscardUnknown(m)
}

var xxx_messageInfo_PingRes proto.InternalMessageInfo

func (m *PingRes) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Test rpc
type TestReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReq) Reset()         { *m = TestReq{} }
func (m *TestReq) String() string { return proto.CompactTextString(m) }
func (*TestReq) ProtoMessage()    {}
func (*TestReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{2}
}

func (m *TestReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReq.Unmarshal(m, b)
}
func (m *TestReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReq.Marshal(b, m, deterministic)
}
func (m *TestReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReq.Merge(m, src)
}
func (m *TestReq) XXX_Size() int {
	return xxx_messageInfo_TestReq.Size(m)
}
func (m *TestReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReq.DiscardUnknown(m)
}

var xxx_messageInfo_TestReq proto.InternalMessageInfo

type TestRes struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRes) Reset()         { *m = TestRes{} }
func (m *TestRes) String() string { return proto.CompactTextString(m) }
func (*TestRes) ProtoMessage()    {}
func (*TestRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{3}
}

func (m *TestRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRes.Unmarshal(m, b)
}
func (m *TestRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRes.Marshal(b, m, deterministic)
}
func (m *TestRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRes.Merge(m, src)
}
func (m *TestRes) XXX_Size() int {
	return xxx_messageInfo_TestRes.Size(m)
}
func (m *TestRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRes.DiscardUnknown(m)
}

var xxx_messageInfo_TestRes proto.InternalMessageInfo

func (m *TestRes) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

// Add upload vouchers rpc
type UploadToPoolReq struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	PoolId               string   `protobuf:"bytes,3,opt,name=poolId,proto3" json:"poolId,omitempty"`
	UploadId             string   `protobuf:"bytes,4,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	Vouchers             []string `protobuf:"bytes,5,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadToPoolReq) Reset()         { *m = UploadToPoolReq{} }
func (m *UploadToPoolReq) String() string { return proto.CompactTextString(m) }
func (*UploadToPoolReq) ProtoMessage()    {}
func (*UploadToPoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{4}
}

func (m *UploadToPoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadToPoolReq.Unmarshal(m, b)
}
func (m *UploadToPoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadToPoolReq.Marshal(b, m, deterministic)
}
func (m *UploadToPoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadToPoolReq.Merge(m, src)
}
func (m *UploadToPoolReq) XXX_Size() int {
	return xxx_messageInfo_UploadToPoolReq.Size(m)
}
func (m *UploadToPoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadToPoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadToPoolReq proto.InternalMessageInfo

func (m *UploadToPoolReq) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *UploadToPoolReq) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *UploadToPoolReq) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *UploadToPoolReq) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *UploadToPoolReq) GetVouchers() []string {
	if m != nil {
		return m.Vouchers
	}
	return nil
}

type UploadToPoolRes struct {
	TotalUpload          int64    `protobuf:"varint,1,opt,name=totalUpload,proto3" json:"totalUpload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadToPoolRes) Reset()         { *m = UploadToPoolRes{} }
func (m *UploadToPoolRes) String() string { return proto.CompactTextString(m) }
func (*UploadToPoolRes) ProtoMessage()    {}
func (*UploadToPoolRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{5}
}

func (m *UploadToPoolRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadToPoolRes.Unmarshal(m, b)
}
func (m *UploadToPoolRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadToPoolRes.Marshal(b, m, deterministic)
}
func (m *UploadToPoolRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadToPoolRes.Merge(m, src)
}
func (m *UploadToPoolRes) XXX_Size() int {
	return xxx_messageInfo_UploadToPoolRes.Size(m)
}
func (m *UploadToPoolRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadToPoolRes.DiscardUnknown(m)
}

var xxx_messageInfo_UploadToPoolRes proto.InternalMessageInfo

func (m *UploadToPoolRes) GetTotalUpload() int64 {
	if m != nil {
		return m.TotalUpload
	}
	return 0
}

// Get pool status rpc
type GetPoolStatusReq struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	PoolIds              []string `protobuf:"bytes,3,rep,name=poolIds,proto3" json:"poolIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPoolStatusReq) Reset()         { *m = GetPoolStatusReq{} }
func (m *GetPoolStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetPoolStatusReq) ProtoMessage()    {}
func (*GetPoolStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{6}
}

func (m *GetPoolStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolStatusReq.Unmarshal(m, b)
}
func (m *GetPoolStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolStatusReq.Marshal(b, m, deterministic)
}
func (m *GetPoolStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolStatusReq.Merge(m, src)
}
func (m *GetPoolStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetPoolStatusReq.Size(m)
}
func (m *GetPoolStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolStatusReq proto.InternalMessageInfo

func (m *GetPoolStatusReq) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GetPoolStatusReq) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *GetPoolStatusReq) GetPoolIds() []string {
	if m != nil {
		return m.PoolIds
	}
	return nil
}

type GetPoolStatusRes struct {
	PoolsStatus          map[string]*GetPoolStatusRes_PoolStatus `protobuf:"bytes,1,rep,name=PoolsStatus,proto3" json:"PoolsStatus,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *GetPoolStatusRes) Reset()         { *m = GetPoolStatusRes{} }
func (m *GetPoolStatusRes) String() string { return proto.CompactTextString(m) }
func (*GetPoolStatusRes) ProtoMessage()    {}
func (*GetPoolStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{7}
}

func (m *GetPoolStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolStatusRes.Unmarshal(m, b)
}
func (m *GetPoolStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolStatusRes.Marshal(b, m, deterministic)
}
func (m *GetPoolStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolStatusRes.Merge(m, src)
}
func (m *GetPoolStatusRes) XXX_Size() int {
	return xxx_messageInfo_GetPoolStatusRes.Size(m)
}
func (m *GetPoolStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolStatusRes proto.InternalMessageInfo

func (m *GetPoolStatusRes) GetPoolsStatus() map[string]*GetPoolStatusRes_PoolStatus {
	if m != nil {
		return m.PoolsStatus
	}
	return nil
}

type GetPoolStatusRes_PoolStatus struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Available            int64    `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPoolStatusRes_PoolStatus) Reset()         { *m = GetPoolStatusRes_PoolStatus{} }
func (m *GetPoolStatusRes_PoolStatus) String() string { return proto.CompactTextString(m) }
func (*GetPoolStatusRes_PoolStatus) ProtoMessage()    {}
func (*GetPoolStatusRes_PoolStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{7, 0}
}

func (m *GetPoolStatusRes_PoolStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolStatusRes_PoolStatus.Unmarshal(m, b)
}
func (m *GetPoolStatusRes_PoolStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolStatusRes_PoolStatus.Marshal(b, m, deterministic)
}
func (m *GetPoolStatusRes_PoolStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolStatusRes_PoolStatus.Merge(m, src)
}
func (m *GetPoolStatusRes_PoolStatus) XXX_Size() int {
	return xxx_messageInfo_GetPoolStatusRes_PoolStatus.Size(m)
}
func (m *GetPoolStatusRes_PoolStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolStatusRes_PoolStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolStatusRes_PoolStatus proto.InternalMessageInfo

func (m *GetPoolStatusRes_PoolStatus) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetPoolStatusRes_PoolStatus) GetAvailable() int64 {
	if m != nil {
		return m.Available
	}
	return 0
}

// Delete all pool uploads vouchers rpc
type DeletePoolReq struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	PoolId               string   `protobuf:"bytes,3,opt,name=poolId,proto3" json:"poolId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePoolReq) Reset()         { *m = DeletePoolReq{} }
func (m *DeletePoolReq) String() string { return proto.CompactTextString(m) }
func (*DeletePoolReq) ProtoMessage()    {}
func (*DeletePoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{8}
}

func (m *DeletePoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePoolReq.Unmarshal(m, b)
}
func (m *DeletePoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePoolReq.Marshal(b, m, deterministic)
}
func (m *DeletePoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePoolReq.Merge(m, src)
}
func (m *DeletePoolReq) XXX_Size() int {
	return xxx_messageInfo_DeletePoolReq.Size(m)
}
func (m *DeletePoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePoolReq proto.InternalMessageInfo

func (m *DeletePoolReq) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *DeletePoolReq) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *DeletePoolReq) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

type DeletePoolRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePoolRes) Reset()         { *m = DeletePoolRes{} }
func (m *DeletePoolRes) String() string { return proto.CompactTextString(m) }
func (*DeletePoolRes) ProtoMessage()    {}
func (*DeletePoolRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e572ab4fba54a2c, []int{9}
}

func (m *DeletePoolRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePoolRes.Unmarshal(m, b)
}
func (m *DeletePoolRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePoolRes.Marshal(b, m, deterministic)
}
func (m *DeletePoolRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePoolRes.Merge(m, src)
}
func (m *DeletePoolRes) XXX_Size() int {
	return xxx_messageInfo_DeletePoolRes.Size(m)
}
func (m *DeletePoolRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePoolRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePoolRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingReq)(nil), "lsvoucherds.PingReq")
	proto.RegisterType((*PingRes)(nil), "lsvoucherds.PingRes")
	proto.RegisterType((*TestReq)(nil), "lsvoucherds.TestReq")
	proto.RegisterType((*TestRes)(nil), "lsvoucherds.TestRes")
	proto.RegisterType((*UploadToPoolReq)(nil), "lsvoucherds.UploadToPoolReq")
	proto.RegisterType((*UploadToPoolRes)(nil), "lsvoucherds.UploadToPoolRes")
	proto.RegisterType((*GetPoolStatusReq)(nil), "lsvoucherds.GetPoolStatusReq")
	proto.RegisterType((*GetPoolStatusRes)(nil), "lsvoucherds.GetPoolStatusRes")
	proto.RegisterMapType((map[string]*GetPoolStatusRes_PoolStatus)(nil), "lsvoucherds.GetPoolStatusRes.PoolsStatusEntry")
	proto.RegisterType((*GetPoolStatusRes_PoolStatus)(nil), "lsvoucherds.GetPoolStatusRes.PoolStatus")
	proto.RegisterType((*DeletePoolReq)(nil), "lsvoucherds.DeletePoolReq")
	proto.RegisterType((*DeletePoolRes)(nil), "lsvoucherds.DeletePoolRes")
}

func init() { proto.RegisterFile("grpc/proto/voucherds.proto", fileDescriptor_1e572ab4fba54a2c) }

var fileDescriptor_1e572ab4fba54a2c = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xe3, 0xa4, 0x69, 0xc6, 0x54, 0x8d, 0x46, 0x15, 0xb2, 0x56, 0x05, 0x45, 0xcb, 0x25,
	0x27, 0x57, 0x4a, 0x39, 0x20, 0x0e, 0x88, 0x03, 0x50, 0xe5, 0x02, 0x91, 0x29, 0x5c, 0x91, 0x1b,
	0xaf, 0x52, 0x8b, 0x25, 0xeb, 0x78, 0xd6, 0x91, 0xfa, 0x2f, 0xb8, 0xf2, 0xdb, 0xf8, 0x33, 0x68,
	0x77, 0xed, 0xc6, 0x36, 0x25, 0x1c, 0x10, 0xb7, 0x7d, 0x6f, 0xde, 0xf3, 0x7c, 0xec, 0x8e, 0x81,
	0xad, 0x8b, 0x7c, 0x75, 0x91, 0x17, 0x4a, 0xab, 0x8b, 0x9d, 0x2a, 0x57, 0xb7, 0xa2, 0x48, 0x29,
	0xb2, 0x18, 0x03, 0x49, 0xf7, 0x14, 0x1f, 0xc3, 0x68, 0x99, 0x6d, 0xd6, 0xb1, 0xd8, 0xf2, 0x67,
	0xf5, 0x91, 0x30, 0x84, 0xd1, 0x4e, 0x14, 0x94, 0xa9, 0x4d, 0xe8, 0x4d, 0xbd, 0xd9, 0x38, 0xae,
	0xa1, 0xd1, 0x5f, 0x0b, 0xd2, 0x95, 0xde, 0x1d, 0xad, 0x3e, 0xa3, 0xcf, 0x89, 0xcc, 0x52, 0xab,
	0x3f, 0x8e, 0x6b, 0xc8, 0x7f, 0x78, 0x70, 0xfa, 0x29, 0x97, 0x2a, 0x49, 0xaf, 0xd5, 0x52, 0x29,
	0x19, 0x8b, 0x2d, 0x3e, 0x86, 0xa3, 0x42, 0xac, 0xf7, 0x1f, 0xaf, 0x10, 0x3e, 0x05, 0x58, 0x95,
	0xa4, 0xd5, 0x37, 0x51, 0x2c, 0xd2, 0xb0, 0x6f, 0x63, 0x0d, 0xc6, 0xf8, 0x72, 0xa5, 0xe4, 0x22,
	0x0d, 0x7d, 0xe7, 0x73, 0x08, 0x19, 0x1c, 0x97, 0x36, 0xc5, 0x22, 0x0d, 0x07, 0x36, 0x72, 0x8f,
	0x4d, 0xac, 0x6a, 0x96, 0xc2, 0xe1, 0xd4, 0x37, 0xb1, 0x1a, 0xf3, 0xcb, 0x6e, 0x69, 0x84, 0x53,
	0x08, 0xb4, 0xd2, 0x89, 0x74, 0xbc, 0xad, 0xcf, 0x8f, 0x9b, 0x14, 0x4f, 0x61, 0x72, 0x25, 0xb4,
	0xd1, 0x7f, 0xd4, 0x89, 0x2e, 0xe9, 0x5f, 0x1a, 0x0a, 0x61, 0xe4, 0x5a, 0xa0, 0xd0, 0xb7, 0xb5,
	0xd5, 0x90, 0x7f, 0xef, 0xff, 0x96, 0x86, 0x70, 0x09, 0x81, 0x21, 0xc8, 0x31, 0xa1, 0x37, 0xf5,
	0x67, 0xc1, 0x3c, 0x8a, 0x1a, 0xd7, 0x19, 0x75, 0x3d, 0x51, 0xc3, 0xf0, 0x76, 0xa3, 0x8b, 0xbb,
	0xb8, 0xf9, 0x09, 0xf6, 0x1a, 0x60, 0x2f, 0xc7, 0x33, 0x18, 0xda, 0x4e, 0xab, 0xb6, 0x1d, 0xc0,
	0x73, 0x18, 0x27, 0xbb, 0x24, 0x93, 0xc9, 0x8d, 0x14, 0xb6, 0x07, 0x3f, 0xde, 0x13, 0xec, 0x16,
	0x26, 0xdd, 0x14, 0x38, 0x01, 0xff, 0xab, 0xb8, 0xab, 0x66, 0x61, 0x8e, 0xf8, 0x0a, 0x86, 0xbb,
	0x44, 0x96, 0xce, 0x1f, 0xcc, 0x67, 0x7f, 0xaf, 0xb9, 0x42, 0xce, 0xf6, 0xb2, 0xff, 0xc2, 0xe3,
	0x5f, 0xe0, 0xe4, 0x8d, 0x90, 0x42, 0x8b, 0xff, 0xf4, 0x8c, 0xf8, 0x69, 0x3b, 0x01, 0xcd, 0x7f,
	0xf6, 0x61, 0x70, 0x55, 0xe4, 0x2b, 0x7c, 0x0e, 0x03, 0xb3, 0x19, 0x78, 0xd6, 0xaa, 0xbb, 0xda,
	0x1b, 0xf6, 0x10, 0x4b, 0xbc, 0x67, 0x5c, 0x66, 0x3f, 0x3a, 0xae, 0x6a, 0x7b, 0xd8, 0x43, 0xac,
	0x71, 0xbd, 0x87, 0x47, 0xcd, 0x47, 0x89, 0xe7, 0x2d, 0x5d, 0x67, 0x95, 0xd8, 0xa1, 0x28, 0xf1,
	0xde, 0xcc, 0xc3, 0x0f, 0x70, 0xd2, 0x1a, 0x30, 0x3e, 0x39, 0x34, 0xfc, 0x2d, 0x3b, 0x18, 0x36,
	0x05, 0xbe, 0x03, 0xd8, 0x8f, 0x09, 0x59, 0x4b, 0xde, 0xba, 0x20, 0xf6, 0xe7, 0x18, 0xf1, 0xde,
	0xcd, 0x91, 0xfd, 0x1b, 0x5d, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x37, 0x11, 0x9c, 0xab,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
	Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestRes, error)
	UploadToPool(ctx context.Context, opts ...grpc.CallOption) (Grpc_UploadToPoolClient, error)
	GetPoolStatus(ctx context.Context, in *GetPoolStatusReq, opts ...grpc.CallOption) (*GetPoolStatusRes, error)
	DeletePool(ctx context.Context, in *DeletePoolReq, opts ...grpc.CallOption) (*DeletePoolRes, error)
}

type grpcClient struct {
	cc *grpc.ClientConn
}

func NewGrpcClient(cc *grpc.ClientConn) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error) {
	out := new(PingRes)
	err := c.cc.Invoke(ctx, "/lsvoucherds.Grpc/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestRes, error) {
	out := new(TestRes)
	err := c.cc.Invoke(ctx, "/lsvoucherds.Grpc/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) UploadToPool(ctx context.Context, opts ...grpc.CallOption) (Grpc_UploadToPoolClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Grpc_serviceDesc.Streams[0], "/lsvoucherds.Grpc/UploadToPool", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcUploadToPoolClient{stream}
	return x, nil
}

type Grpc_UploadToPoolClient interface {
	Send(*UploadToPoolReq) error
	CloseAndRecv() (*UploadToPoolRes, error)
	grpc.ClientStream
}

type grpcUploadToPoolClient struct {
	grpc.ClientStream
}

func (x *grpcUploadToPoolClient) Send(m *UploadToPoolReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcUploadToPoolClient) CloseAndRecv() (*UploadToPoolRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadToPoolRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcClient) GetPoolStatus(ctx context.Context, in *GetPoolStatusReq, opts ...grpc.CallOption) (*GetPoolStatusRes, error) {
	out := new(GetPoolStatusRes)
	err := c.cc.Invoke(ctx, "/lsvoucherds.Grpc/GetPoolStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) DeletePool(ctx context.Context, in *DeletePoolReq, opts ...grpc.CallOption) (*DeletePoolRes, error) {
	out := new(DeletePoolRes)
	err := c.cc.Invoke(ctx, "/lsvoucherds.Grpc/DeletePool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServer is the server API for Grpc service.
type GrpcServer interface {
	Ping(context.Context, *PingReq) (*PingRes, error)
	Test(context.Context, *TestReq) (*TestRes, error)
	UploadToPool(Grpc_UploadToPoolServer) error
	GetPoolStatus(context.Context, *GetPoolStatusReq) (*GetPoolStatusRes, error)
	DeletePool(context.Context, *DeletePoolReq) (*DeletePoolRes, error)
}

func RegisterGrpcServer(s *grpc.Server, srv GrpcServer) {
	s.RegisterService(&_Grpc_serviceDesc, srv)
}

func _Grpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsvoucherds.Grpc/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsvoucherds.Grpc/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Test(ctx, req.(*TestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_UploadToPool_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).UploadToPool(&grpcUploadToPoolServer{stream})
}

type Grpc_UploadToPoolServer interface {
	SendAndClose(*UploadToPoolRes) error
	Recv() (*UploadToPoolReq, error)
	grpc.ServerStream
}

type grpcUploadToPoolServer struct {
	grpc.ServerStream
}

func (x *grpcUploadToPoolServer) SendAndClose(m *UploadToPoolRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcUploadToPoolServer) Recv() (*UploadToPoolReq, error) {
	m := new(UploadToPoolReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Grpc_GetPoolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).GetPoolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsvoucherds.Grpc/GetPoolStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).GetPoolStatus(ctx, req.(*GetPoolStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_DeletePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).DeletePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsvoucherds.Grpc/DeletePool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).DeletePool(ctx, req.(*DeletePoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lsvoucherds.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Grpc_Ping_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _Grpc_Test_Handler,
		},
		{
			MethodName: "GetPoolStatus",
			Handler:    _Grpc_GetPoolStatus_Handler,
		},
		{
			MethodName: "DeletePool",
			Handler:    _Grpc_DeletePool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadToPool",
			Handler:       _Grpc_UploadToPool_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/proto/voucherds.proto",
}
